# main text of home
name: Michel Combes
bio: A life hacker at the service of humanity
port: 4000

# twitter summary info
description: A blog about technology, blockchains and related stuff

picture: assets/images/michelc.png

name: mystifying-easley-53776d
# your url: http://michel47.github.io
#url: http://koppl.in/violet
#url: http://michelc.neocities.org
#url: https://michelc.tk
#url: http://ocean.local:8088/web/michelc.tk
url: https://mystifying-easley-53776d.netlify.com

# if you don't have any of social below, comment the line
facebook: mgcombs
twitter: mgcombes
github: michel47
email: michelc@gc-bank.org

plugins:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
